### ISSUE TITLE
Fix file paths on tarbell job submission scripts

### ISSUE THREAD

**Issue by mbjoseph** [jrmihalj/HPV#4]
For all of the tarbell submission scripts (in code/shell), the paths referencing the model fitting files need to be fixed: 

- [x] Because our GitHub repository is "HPV", the directory on tarbell should also be called "HPV". 

- [x] Change the file paths in the shell scripts to reflect updated structure (e.g., `code/R/fit_model_tarbell.R`). I am going to let 
@jrmihalj  or @slr72090 do this, since I'm not sure whether you need to specify an absolute path (e.g., `~/HPV/code/R/fit_model_tarbell.R`) or whether you can use a relative path (e.g., `code/R/fit_model_tarbell.R`).

**Comment by mbjoseph** [comment]
Second box is checked with 6aef2b332e52d997600f95b885274c0d248d537b

**Comment by jrmihalj** [comment]
first box checked with b1a89e7b11f82edfc86472f7667b884768c99170
