### ISSUE TITLE
Check over generated likelihoods for waic

### ISSUE THREAD

**Issue by slr72090** [jrmihalj/HPV#6]
Double check me on the log likelihood calculation for the waic. 
For the models without the correlations, the log likelihood vector is an (n_obs x n_strains) matrix, whereas for the models with correlations, the log likelihood vector is an n_obs vector. My intuition is that we can sum across rows to get the n_obs log likelihood vector for the models without correlations, since the likelihoods of each strain at each observation are independent (this can be done after the likelihood is extracted). But let me know - i might have messed this up.

**Comment by jrmihalj** [comment]
I checked this. There was a slight mis-specification. Should be using multi_normal_cholesky_log, but this is still stored into a matrix.

**Comment by slr72090** [comment]
Thanks, Joe!
